version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: weekly
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: weekly
    groups:
      docs-dependencies:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
    groups:
      poetry-dependencies:
        patterns:
          - "*"
