# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/fpe_ffx.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper


# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13proto/fpe_ffx.proto\x12\x0fssb.crypto.tink"]\n\x0f\x46peFfxKeyParams\x12\x10\n\x08key_size\x18\x01 \x01(\r\x12&\n\x04mode\x18\x02 \x01(\x0e\x32\x18.ssb.crypto.tink.FfxMode\x12\x10\n\x08\x61lphabet\x18\x03 \x01(\t"f\n\x0f\x46peFfxKeyFormat\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x10\n\x08key_size\x18\x02 \x01(\r\x12\x30\n\x06params\x18\x03 \x01(\x0b\x32 .ssb.crypto.tink.FpeFfxKeyParams"a\n\tFpeFfxKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x11\n\tkey_value\x18\x02 \x01(\x0c\x12\x30\n\x06params\x18\x03 \x01(\x0b\x32 .ssb.crypto.tink.FpeFfxKeyParams*%\n\x07\x46\x66xMode\x12\x07\n\x03\x46\x46\x31\x10\x00\x12\x07\n\x03\x46\x46\x33\x10\x01\x12\x08\n\x04\x46\x46\x33\x31\x10\x02\x42\x1c\n\x18no.ssb.crypto.tink.protoP\x01\x62\x06proto3'
)

_FFXMODE = DESCRIPTOR.enum_types_by_name["FfxMode"]
FfxMode = enum_type_wrapper.EnumTypeWrapper(_FFXMODE)
FF1 = 0
FF3 = 1
FF31 = 2


_FPEFFXKEYPARAMS = DESCRIPTOR.message_types_by_name["FpeFfxKeyParams"]
_FPEFFXKEYFORMAT = DESCRIPTOR.message_types_by_name["FpeFfxKeyFormat"]
_FPEFFXKEY = DESCRIPTOR.message_types_by_name["FpeFfxKey"]
FpeFfxKeyParams = _reflection.GeneratedProtocolMessageType(
    "FpeFfxKeyParams",
    (_message.Message,),
    {
        "DESCRIPTOR": _FPEFFXKEYPARAMS,
        "__module__": "proto.fpe_ffx_pb2"
        # @@protoc_insertion_point(class_scope:ssb.crypto.tink.FpeFfxKeyParams)
    },
)
_sym_db.RegisterMessage(FpeFfxKeyParams)

FpeFfxKeyFormat = _reflection.GeneratedProtocolMessageType(
    "FpeFfxKeyFormat",
    (_message.Message,),
    {
        "DESCRIPTOR": _FPEFFXKEYFORMAT,
        "__module__": "proto.fpe_ffx_pb2"
        # @@protoc_insertion_point(class_scope:ssb.crypto.tink.FpeFfxKeyFormat)
    },
)
_sym_db.RegisterMessage(FpeFfxKeyFormat)

FpeFfxKey = _reflection.GeneratedProtocolMessageType(
    "FpeFfxKey",
    (_message.Message,),
    {
        "DESCRIPTOR": _FPEFFXKEY,
        "__module__": "proto.fpe_ffx_pb2"
        # @@protoc_insertion_point(class_scope:ssb.crypto.tink.FpeFfxKey)
    },
)
_sym_db.RegisterMessage(FpeFfxKey)

if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\030no.ssb.crypto.tink.protoP\001"
    _FFXMODE._serialized_start = 338
    _FFXMODE._serialized_end = 375
    _FPEFFXKEYPARAMS._serialized_start = 40
    _FPEFFXKEYPARAMS._serialized_end = 133
    _FPEFFXKEYFORMAT._serialized_start = 135
    _FPEFFXKEYFORMAT._serialized_end = 237
    _FPEFFXKEY._serialized_start = 239
    _FPEFFXKEY._serialized_end = 336
# @@protoc_insertion_point(module_scope)
