name: Scheduled update

on:
  schedule:
    # 07:00 on Fridays
    - cron: "0 7 * * Fri"
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-dependencies:
    uses: statisticsnorway/dependency-updater-python@fix-app-git-config
    secrets: inherit
