name: Scheduled update

on:
  schedule:
    # 07:00 on Fridays
    - cron: "0 7 * * Fri"
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@0d49dd721133f900ebd5e0dff2810704e8defbc6
        with:
          app_id: ${{ secrets.DEPENDENCY_UPDATER_PYTHON_ID }}
          private_key: ${{ secrets.DEPENDENCY_UPDATER_PYTHON_PRIVATE_KEY }}
      - uses: statisticsnorway/dependency-updater-python@fix-app-git-config
        with:
          token: ${{ steps.generate_token.outputs.token }}
